name = "MultiQuad"
uuid = "8fca5bbe-a785-4bb7-9793-c0c8ddca5d4b"
authors = ["Aurelio Amerio <aure.amerio@gmail.com>"]
version = "1.0.0"

[deps]
Cuba = "8a292aeb-7a57-582c-b821-06e4c11590b1"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
Cuba = "^2.0.0"
QuadGK = "^2.3.1"
Unitful = "^0.18.0"
julia = "^1.0.0"
